apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-user: "user-app"
  mysql-database: "demo_country_api"
  init.sql: |
    CREATE TABLE country (
        code VARCHAR(2) PRIMARY KEY,
        name VARCHAR(100) NOT NULL
    );
    
    INSERT INTO country (code, name) VALUES 
    ('ES', 'España'),
    ('US', 'Estados Unidos'),
    ('MX', 'México'),
    ('AR', 'Argentina'),
    ('BR', 'Brasil'),
    ('CO', 'Colombia'),
    ('PE', 'Perú'),
    ('CL', 'Chile');
