apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: dHJhc3Rl # traste encoded in base64
  mysql-user-password: MTIzNDVxYXp3JA==  # 12345qazw$ encoded in base64
